version: "3"
services: 
  web:
    command: npm run start
    container_name: corporate-moon-prod
    build: './server'
    ports: 
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always
