version: "3"
services: 
  client:
    command: npm run serve
    container_name: mevn-app-client
    build: ./client
    ports: 
      - "8080:8080"
    environment:
      - NODE_ENV=development
  server: 
    command: npm run dev
    container_name: mevn-app-server
    build: ./server
    ports: 
      - "5000:5000"
    environment:
      - NODE_ENV=development